[package]
name = "thinkdsp"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32"       # motor base de egui para apps nativas
egui = "0.32"
egui_plot = "0.33"
env_logger = "0.11"
log = "0.4"
fundsp = "0.20.0"